config/routes.rb
Rails.application.routes.draw do
  root  'contacts#new'
  resources :contacts, except: [:show]
  resources :filters, only: [:new, :index]
  
  post 'filters' => 'filters#index'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  before_save { self.email = email.downcase }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :name, presence: true, length: { minimum: 5, maximum: 50 }
  validates :age, numericality: { only_integer: true }
  validates :role, presence: true, length: { minimum: 5, maximum: 50 }
  validates :state, presence: true
  
  def self.search(params)
    op_state = default_if_empty(params[:op_state], "AND")
    state = params[:state]
    op_role = default_if_empty(params[:op_role], "AND")
    role = params[:role]
    from = default_if_empty(params[:age_from], 0)
    to = default_if_empty(params[:age_to], 115)
    
    search_params(from, to, op_state, state, op_role, role)
  end
  
  def self.search_by_filter(filter)
    @filter = Filter.find(filter)
    @filter.age_from ||= 0
    @filter.age_to ||= 115
    @filter.op_state ||= "AND"
    @filter.op_role ||= "AND"
    search_params(@filter.age_from, @filter.age_to, @filter.op_state, @filter.state, @filter.op_role, @filter.role)
  end

  private
  
  def self.search_params(from, to, op_state, state, op_role, role)
    age_filter = "age BETWEEN #{from} AND #{to}"
    if state.empty? && role.empty?
      Contact.where(age_filter)
    elsif state.empty?
      Contact.where("#{age_filter} #{op_role} role = '#{role}'")
    elsif role.empty?
      Contact.where("#{age_filter} #{op_state} state = '#{state}'")
    else
      Contact.where("#{age_filter} #{op_state} state = '#{state}' #{op_role} role = '#{role}'")
    end
  end
  
  def self.default_if_empty(param, default)
    if param.nil? || param.empty?; default else param end
  end
end

app/models/filter.rb
class Filter < ActiveRecord::Base
  validates :filter_name, presence: true
end

app/models/state.rb
class State < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new
    @contact = Contact.new
    @states = State.all
  end
  
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = t :contact_created
      redirect_to contacts_path
    else
      @states = State.all
      render 'new'
    end
  end

  def index
    @contacts_page = Contact.paginate(page: params[:page], per_page: 10)
    
    if params.has_key?(:filter)
      if save_filter_params == t(:save_filter)
        redirect_to new_filter_path params
      else
        @contacts = @contacts_page.search(filter_params)
      end
    elsif params.has_key?(:selected_filter) && load_filter_params != t(:select)
      @contacts = @contacts_page.search_by_filter(load_filter_params)
    else
      @contacts = @contacts_page.all.order(:name)
    end
    

    @filter = Filter.new
    @states = State.all
    @roles = Contact.select(:role).uniq.order(:role)
    @filters = Filter.select(:id, :filter_name).order(:filter_name)
  end
  
  private
  
  def contact_params
    params.require(:contact).permit(:name, :email, :age, :state, :role, :age_to, :age_from, :op_state, :op_role)
  end
  
  def filter_params
    params.require(:filter).permit(:filter_name, :age_from, :age_to, :op_state, :state, :op_role, :role)
  end
  
  def save_filter_params
    params.require(:commit)
  end
  
  def load_filter_params
    params.require(:selected_filter)
  end
end

app/controllers/filters_controller.rb
class FiltersController < ApplicationController
  def index
    if params.has_key?(:filter)
      if save_filter_params == t(:save_filter)
        redirect_to new_filter_path params
      else
        params.delete :authenticity_token
        redirect_to contacts_path params
      end
    elsif params.has_key?(:selected_filter) && load_filter_params != t(:select)
      redirect_to contacts_path Contact.search_by_filter(load_filter_params)
    else
      redirect_to contacts_path Contact.all.order(:name)
    end
  end
  
  def new
    @filter = Filter.new(filter_params)
    if @filter.save
      flash[:success] = t :filter_created
    else
      flash[:danger] = @filter.errors.full_messages.first
    end
    redirect_to contacts_path
  end
  
  private
  
  def filter_params
    params.require(:filter).permit(:filter_name, :age_from, :age_to, :op_state, :state, :op_role, :role)
  end
  
  def save_filter_params
    params.require(:commit)
  end
  
  def load_filter_params
    params.require(:selected_filter)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/views/contacts/_contact.html.erb
<tr>
  <td><%= contact.name %></td>
  <td><%= contact.email %></td>
  <td><%= contact.age %></td>
  <td><%= contact.state %></td>
  <td><%= contact.role %></td>
</tr>

app/views/contacts/_filter.html.erb
<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          <%= t :contact_filter%>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">

        
        <%= form_for @filter do |f| %>
          <h3><%= t :age_range %></h3>
          <%= f.label :from, t(:from) %>
          <%= f.text_field :age_from, value: (params[:filter].nil? ? "" : params[:filter][:age_from]), type: :number, min: 0, max: 114, class: "form-control" %><br />
          <%= f.label :to, t(:to) %>
          <%= f.text_field :age_to, value: (params[:filter].nil? ? "" : params[:filter][:age_to]), type: :number, min: 1, max: 115, class: "form-control" %>
          
          <h3><%= t :state, scope: [:activerecord, :attributes, :contact ] %></h3>
          <div class="btn-group" data-toggle="buttons">
            <%= f.label :and_label, "E", class: 'btn btn-primary' + (!params[:filter].nil? && params[:filter][:op_state] == "AND" ? ' active' : '') do %>
              <%= f.radio_button :op_state, "AND", checked: !!(!params[:filter].nil? && params[:filter][:op_state] == "AND") %><%= t :and %>
            <% end %>
            <%= f.label :or_lable, "OU", class: 'btn btn-primary' + (!params[:filter].nil? && params[:filter][:op_state] == "OR" ? ' active' : '') do %>
              <%= f.radio_button :op_state, "OR", checked: !!(!params[:filter].nil? && params[:filter][:op_state] == "OR") %><%= t :or %>
            <% end %>
          </div><br /><br />
          <%= f.select :state, content_tag(:option,"")+options_from_collection_for_select(@states, "state_id", "state", (params[:filter].nil? ? "" : params[:filter][:state])), {}, { class: 'form-control' } %>
          
          <h3><%= t :role, scope: [:activerecord, :attributes, :contact ] %></h3>
          <div class="btn-group" data-toggle="buttons">
            <%= f.label :and_label, "E", class: 'btn btn-primary' + (!params[:filter].nil? && params[:filter][:op_role] == "AND" ? ' active' : '') do %>
              <%= f.radio_button :op_role, "AND", checked: !!(!params[:filter].nil? && params[:filter][:op_role] == "AND") %><%= t :and %>
            <% end %>
            <%= f.label :or_lable, "OU", class: 'btn btn-primary' + (!params[:filter].nil? && params[:filter][:op_role] == "OR" ? ' active' : '') do %>
              <%= f.radio_button :op_role, "OR", checked: !!(!params[:filter].nil? && params[:filter][:op_role] == "OR") %><%= t :or %>
            <% end %>
          </div><br /><br />
          <%= f.select :role, content_tag(:option,"")+options_from_collection_for_select(@roles, "role", "role", (params[:filter].nil? ? "" : params[:filter][:role])), {}, { class: 'form-control' } %><br />
        
          <%= f.submit t(:apply), class: "btn btn-default" %>
          
          <%= render partial: 'contacts/save_filter_modal', locals: { f: f } %>
          <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#myModal">
            <%= t :save_filter %>
          </button>
        <% end %>
        
      </div>
    </div>
  </div>
</div>

app/views/contacts/_save_filter_modal.html.erb
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Qual nome deseja dar para o filtro?</h4>
      </div>
      <div class="modal-body">
        <%= f.text_field :filter_name, class: 'form-control', placeholder: "Novo filtro" %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal"><%= t :close %></button>
        <%= submit_tag t(:save_filter), class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/contacts/edit.html.erb
<h1>Contacts#edit</h1>
<p>Find me in app/views/contacts/edit.html.erb</p>

app/views/contacts/index.html.erb
<div class="row">
  <div class="col-xs-12 col-sm-3">
    
    <%= render 'contacts/filter' %>
  </div>
  <div class="col-xs-12 col-sm-9">
    
    <div class="page-header">
    <%= form_tag contacts_path, method: 'get', class: 'form-inline' do %>
      <%= label_tag :saved_filters, t(:saved_filters) %>
      <%= select_tag "selected_filter", content_tag(:option,t(:select))+options_from_collection_for_select(@filters, "id", "filter_name"), class: 'form-control' %>
      <%= submit_tag t(:apply), class: "btn btn-default" %>
    <% end %>
    </div>
    
    <table class="table table-striped">
      <thead>
        <tr>
          <th><%= t :name, scope: [:activerecord, :attributes, :contact ]%></th>
          <th><%= t :email, scope: [:activerecord, :attributes, :contact ] %></th>
          <th><%= t :age, scope: [:activerecord, :attributes, :contact ] %></th>
          <th><%= t :state, scope: [:activerecord, :attributes, :contact ] %></th>
          <th><%= t :role, scope: [:activerecord, :attributes, :contact ] %></th>
        </tr>
      </thead>
      
      <%= render @contacts %>
    </table>
    <%= will_paginate %>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="row">
  <div class="col-sm-2"></div>
  <div class="col-xs-12 col-sm-8">
  <div class="panel panel-default">
    <div class="panel-heading"><h4><%= t :new_contact %></h4></div>
  <div class="panel-body">
  <%= form_for @contact do |f| %>
    <%= render partial: 'shared/error_messages', locals: { obj: @contact } %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :age %>
      <%= f.text_field :age, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.label :state %>
      <%= f.select :state, {},{} , class: 'form-control' do %>
        <% @states.each do |c| %>
         <%= content_tag(:option, c.state, value: c.state_id) %>
        <% end %>
      <% end %>
    </div>

    <div class="form-group">
      <%= f.label :role %>
      <%= f.text_field :role, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.submit t(:create_contact), class: "btn btn-primary" %>
    </div>
  <% end %>
  </div>
  </div>
  </div>
  <div class="col-sm-2"></div>
</div>

app/views/filters/new.html.erb
<h1>Filters#new</h1>
<p>Find me in app/views/filters/new.html.erb</p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Client filtering
    by <a href="http://www.github.com/guifigueiroa">Guilherme Figueiroa</a>
  </small>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" 
              aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Client filtering", contacts_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if controller_name == 'contacts' && action_name == 'new' %>
          <li class="active">
        <% else %>
          <li>
        <%end%>
          <%= link_to t(:new_contact), new_contact_path %>
        </li>
        <% if controller_name == 'contacts' && action_name == 'index' %>
          <li class="active">
        <% else %>
          <li>
        <%end%>
          <%= link_to t(:contact_filter), contacts_path %>
        </li>
      </ul>
      
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>ClientFiltering</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      
      <%= render 'layouts/footer' %>
      <br />
      <%= debug(params) if Rails.env.development? %>
    </div>

</body>
</html>

app/views/shared/_error_messages.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= t :validation, scope: [ :activerecord, :errors], count: obj.errors.count %>
    </div>
    <ul>
    <% obj.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>